version: '3.6'
services:
  www:
    build:
      context: .
      dockerfile: Dockerfile.www
    volumes:
      - "./www:/var/www/html"
      - "./db:/var/www/db"
    ports:
      - 80:80
      - 443:443
