version: '3.6'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: e9w86036f78sd9
    volumes:
      - "./database:/var/lib/mysql"
  db_pma:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 8082:80
    environment:
      MYSQL_ROOT_PASSWORD: e9w86036f78sd9
      PMA_USER: root
      PMA_PASSWORD: e9w86036f78sd9
  www:
    build:
      context: .
      dockerfile: Dockerfile.www
    depends_on:
    - db
    volumes:
      - "./www:/var/www/html"
    ports:
      - 8080:80
